version: "3.9"
services:
  frontend:
    image: nginx:1.15.12-alpine
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - 8080:80
    environment:
      - NGINX_HOST=amor.test
      - NGINX_PORT=80
